@baseUrl = http://localhost:3000

### Read all products
GET {{baseUrl}}/products

### Read one by id
GET http://localhost:3000/products/4

### Read one by id (404 don't exist)
GET {{baseUrl}}/products/10

### Read all products ordered by name
GET {{baseUrl}}/products?order=name

### Read all products ordered by name (reverse order)
GET {{baseUrl}}/products?order=-name

### Create a product
POST {{baseUrl}}/products
Content-Type: application/json

{
    "brand": "Apple",
    "name": "MacBook Pro 14 QWERTY",
    "price": 1400,
    "category": "Ordinateur Portable"
}
