@baseUrl = http://localhost:3001

### Read all products
GET {{baseUrl}}/products

### Read all products filtered by category (category name that contains ampersand)
GET {{baseUrl}}/products?category=Imprimantes%20%26%20périphériques

### Read all products filtered by category (category name that contains blank space)
GET {{baseUrl}}/products?category=Ordinateur%20Portable

### Read one by id
GET {{baseUrl}}/products/2

### Read one by id (404 don't exist)
GET {{baseUrl}}/products/10

### Read all products ordered by name
GET {{baseUrl}}/products?order=name

### Read all products ordered by name (reverse order)
GET {{baseUrl}}/products?order=-name

### Create a product
POST {{baseUrl}}/products
Content-Type: application/json

{
    "brand": "Apple",
    "name": "MacBook Pro 14 QWERTY",
    "price": 1400,
    "category": "Ordinateur Portable"
}

### DELETE product by ID
DELETE {{baseUrl}}/products/6

### UPDATE the product by ID 5
PATCH {{baseUrl}}/products/5
Content-Type: application/json

{
    "stars": 1
}

### GET Static image
GET {{baseUrl}}/photos/LIP_15ALC6.jpg

### GET all categories
GET {{baseUrl}}/products/categories